version: "3.0"

services:
  mysql_db:
    image: mysql:5.6
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_name

  mysql_dumper:
    build: ../src
    environment:
      CRON: "* * * * *"

      DATABASE_TYPE: "MySQL" # [MySQL, PostgreSQL]
      DATABASE_HOST: "mysql_db"
      DATABASE_NAME: "example_name"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "example_password"

      GLACIER_REGION: "eu-central-1" # AWS Region where glacier vault will be created
      GLACIER_VAULT_NAME: "example_vault_name"

      AWS_ACCESS_KEY_ID: "example_access_key"
      AWS_SECRET_ACCESS_KEY: "example_secret_key"